site_name: Monity Wiki
site_url: https://monity.wiki

nav:
  - Home: index.md
  - MonityConfigPanel : monityConfigPanel.md
  - MonityServer : monityServer.md
  - MonityClient : monityClient.md
  - MonityUI : monityUI.md

theme: readthedocs