site_name: Monity Wiki

nav:
  - Home: index.md
  - Monity App: 
    - Overview: MonityApp/index.md

  - Monity Mirror:
    - Overview: MonityMirror/index.md

  - Monity Protocols:
    - Overview: MonityProtocols/index.md
    - Types:
      - Metric: MonityProtocols/Types/Metric.md
      - MetricType: MonityProtocols/Types/MetricType.md
      - MetricUnit: MonityProtocols/Types/MetricUnit.md
    - Commands: MonityProtocols/Commands.md

theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
